// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARYv-AREYtLDRAQYADMibL3PtmNX0U4Ws',
    appId: '1:846932115430:web:f4fdd0a0dd258adf19e027',
    messagingSenderId: '846932115430',
    projectId: 'todo-app-75a4c',
    authDomain: 'todo-app-75a4c.firebaseapp.com',
    storageBucket: 'todo-app-75a4c.firebasestorage.app',
    measurementId: 'G-XC3QX1FX4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbw8s6f7EyQf7nZ4mZKu8bZA2We3EVpA8',
    appId: '1:846932115430:android:d7c7a041a8d47c3419e027',
    messagingSenderId: '846932115430',
    projectId: 'todo-app-75a4c',
    storageBucket: 'todo-app-75a4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0MJERSdLbgVJR0l0kgoVdOPRr764zPo',
    appId: '1:846932115430:ios:a024d60719cc150519e027',
    messagingSenderId: '846932115430',
    projectId: 'todo-app-75a4c',
    storageBucket: 'todo-app-75a4c.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0MJERSdLbgVJR0l0kgoVdOPRr764zPo',
    appId: '1:846932115430:ios:a024d60719cc150519e027',
    messagingSenderId: '846932115430',
    projectId: 'todo-app-75a4c',
    storageBucket: 'todo-app-75a4c.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARYv-AREYtLDRAQYADMibL3PtmNX0U4Ws',
    appId: '1:846932115430:web:940b78da7561e66119e027',
    messagingSenderId: '846932115430',
    projectId: 'todo-app-75a4c',
    authDomain: 'todo-app-75a4c.firebaseapp.com',
    storageBucket: 'todo-app-75a4c.firebasestorage.app',
    measurementId: 'G-72QVMJFH9V',
  );
}
